#!/usr/bin/env python3
"""Shared deterministic generation and installation helpers for Lisa on Codex."""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import tempfile
import tomllib
from pathlib import Path
from typing import Any

AGENT_FILE = "gemskills-content.toml"
AGENT_NAME = "gemskills_content"
MANIFEST_FILE = "manifest.json"
OWNERSHIP_FILE = ".gemskills-agents.json"
SOURCE_FILE = "agents/content.md"
SCHEMA_VERSION = "1"

CODEX_PRELUDE = """# Codex compatibility prelude (Gemskills)

You are running as the Codex custom-agent adapter for Lisa. Preserve the role,
constraints, and output style in the canonical Gemskills prompt below.

## Runtime translation (Claude Code to Codex)

- For `Skill` or `gemskills:<name>`, locate the matching Gemskills `SKILL.md`
  exposed to this Codex session, read it completely, and follow it. Never invent
  a skill or bypass its bundled scripts with a direct provider API call.
- Use Codex filesystem, shell, image-generation, planning, and collaboration
  tools in place of Claude's `Read`, `Write`, `Bash`, and `TodoWrite` tools.
- `${CLAUDE_PLUGIN_ROOT}` means the installed Gemskills plugin root. Resolve
  scripts and assets from the selected skill directory or its plugin root.
- Claude model routing is informational only; inherit the Codex session model.
- Do not edit global Codex configuration or assume Claude-only plugin commands.

---
"""


def sha256(data: bytes) -> str:
    return "sha256:" + hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256(path.read_bytes())


def plugin_root(start: Path | None = None) -> Path:
    env = os.environ.get("GEMSKILLS_PLUGIN_ROOT") or os.environ.get("CLAUDE_PLUGIN_ROOT")
    if env:
        root = Path(env).expanduser().resolve()
        if (root / SOURCE_FILE).is_file():
            return root
        raise SystemExit(f"Gemskills plugin root is invalid: {root}")
    here = (start or Path(__file__)).resolve()
    for parent in [here, *here.parents]:
        if (parent / SOURCE_FILE).is_file():
            return parent
    raise SystemExit("Could not locate the Gemskills plugin root")


def parse_source(path: Path) -> dict[str, str]:
    raw = path.read_text(encoding="utf-8")
    match = re.match(r"\A---\r?\n(.*?)\r?\n---\r?\n(.*)\Z", raw, re.DOTALL)
    if not match:
        raise ValueError(f"{path}: invalid agent frontmatter")
    frontmatter, body = match.groups()
    fields: dict[str, str] = {}
    lines = frontmatter.splitlines()
    index = 0
    while index < len(lines):
        field = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", lines[index])
        if not field:
            index += 1
            continue
        key, value = field.groups()
        if value.strip() in {">", ">-", "|", "|-"}:
            folded = value.strip().startswith(">")
            index += 1
            block: list[str] = []
            while index < len(lines) and (not lines[index] or lines[index][0].isspace()):
                block.append(lines[index].strip())
                index += 1
            fields[key] = (" " if folded else "\n").join(block).strip()
            continue
        fields[key] = value.strip().strip("\"'")
        index += 1
    if not fields.get("description") or not fields.get("version"):
        raise ValueError(f"{path}: description and version are required")
    return {"raw": raw, "description": fields["description"], "version": fields["version"], "body": body}


def toml_multiline(value: str) -> str:
    # TOML basic multiline strings preserve newlines but still interpret
    # backslash escapes. Escape authored Markdown before wrapping it.
    escaped = value.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return '"""' + escaped + '"""'


def generated_text(source: dict[str, str]) -> str:
    source_hash = sha256(source["raw"].encode())
    instructions = CODEX_PRELUDE + "\n" + source["body"]
    return (
        "# Generated by scripts/codex-agents/generate.py — DO NOT EDIT BY HAND\n"
        f"# source: {SOURCE_FILE}\n"
        f"# source_version: {source['version']}\n"
        f"# source_hash: {source_hash}\n"
        f"# generator_schema_version: {SCHEMA_VERSION}\n\n"
        f'name = "{AGENT_NAME}"\n'
        f"description = {toml_multiline(source['description'])}\n"
        f"developer_instructions = {toml_multiline(instructions)}\n"
    )


def build(root: Path) -> tuple[str, dict[str, Any]]:
    source = parse_source(root / SOURCE_FILE)
    text = generated_text(source)
    entry = {
        "source_name": "content",
        "source_path": SOURCE_FILE,
        "source_version": source["version"],
        "source_hash": sha256(source["raw"].encode()),
        "generated_file": AGENT_FILE,
        "generated_hash": sha256(text.encode()),
        "agent_name": AGENT_NAME,
        "default_install": True,
    }
    manifest = {"schema_version": "1", "generator_schema_version": SCHEMA_VERSION, "manager": "gemskills", "agents": [entry]}
    return text, manifest


def json_text(value: Any) -> str:
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


def atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_name, path)
    finally:
        Path(temp_name).unlink(missing_ok=True)


def atomic_copy(source: Path, target: Path) -> None:
    atomic_write(target, source.read_text(encoding="utf-8"))


def load_json(path: Path, default: Any) -> Any:
    if not path.is_file():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def validate_adapter(path: Path) -> None:
    with path.open("rb") as handle:
        parsed = tomllib.load(handle)
    if parsed.get("name") != AGENT_NAME:
        raise ValueError(f"{path}: unexpected agent name")


def quarantine(path: Path, target_dir: Path) -> Path:
    trash = target_dir / ".gemskills-agents-trash"
    trash.mkdir(parents=True, exist_ok=True)
    destination = trash / path.name
    counter = 1
    while destination.exists():
        destination = trash / f"{path.name}.{counter}"
        counter += 1
    shutil.move(path, destination)
    return destination
